CREATE DATABASE GROCERY;
USE GROCERY;

-- 1. Suppliers Table
alter table suppliers
add primary key (supplierid);

select*from suppliers;
 
 -- 2. Categories Table

select*from categories;
alter table categories
add primary key (categoryID);


-- 3. Employees Table
select *from employees;
alter table employees 
add primary key (employeeid);


-- 4. Customers Table
select*from customers;

alter table customers
add primary key(customerid);


-- 5. Products Table
select *from products;
alter table products
add primary key (productid);

alter table products
add constraint fk_suppliers
foreign key(supplierid) references suppliers(supplierid)
ON UPDATE CASCADE ON DELETE CASCADE,
ADD CONSTRAINT FK_CATEGORY
FOREIGN KEY (categoryid)
REFERENCES categories(categoryid)
ON UPDATE CASCADE ON DELETE CASCADE;

-- 6. Orders Table
select *from orders;
alter table orders
add primary key (orderid);

alter table orders
add constraint fk_customers
foreign key(customerid) references customers(customerid)
on update cascade on delete cascade,
add constraint fk_employees
foreign key(employeeid) references employees(employeeid)
on update cascade on delete cascade;


-- 7. Orderdetails Table

alter table orderdetails
add constraint fk_products
foreign key(productid) references products(productid)
on update cascade on delete cascade,
add constraint fk_orders
foreign key(orderid) references orders(orderid)
on update cascade on delete cascade;
select*from orderdetails;



-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- ● How many unique customers have placed orders?
SELECT COUNT(DISTINCT customerid) as unique_customer from orders;

-- Which customers have placed the highest number of orders?
select customerid,count(*) as cust_highest_order from orders group by customerid order by cust_highest_order desc limit 1;

-- ● What is the total and average purchase value per customer?
SELECT customerid,
sum(od.totalprice) as total_purchase,
avg(od.totalprice) as avg_purchase
from orders o
JOIN orderdetails od 
ON o.orderid  = od.orderid
GROUP BY o.customerid;


-- ● Who are the top 5 customers by total purchase amount?
SELECT customerid,
sum(od.totalprice) as total_purchase
from orders o
JOIN orderdetails as od 
on o.orderid = od.orderid
group by customerid
order by total_purchase desc limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- ● How many products exist in each category?
select *from products;
select*from categories;
select categoryid,count(*) as total_products from products group by categoryid;
select c.categoryname,
count(p.productid) as total_products
from categories c
join  products p
on c.categoryid = p.categoryid
group by categoryname;



-- ● What is the average price of products by category?
select categoryid,avg(price) from products group by categoryid;
select c.categoryname,
avg(p.price) as avg_price
from categories c 
join products p 
 on c.categoryid   = p.productid
 group by categoryname;
 
 
 -- ● Which products have the highest total sales volume (by quantity)?
 select p.productid,
 sum(od.quantity) as highest_quantity_sold
 from products p
 join orderdetails od 
 on od.productid = p.productid
 group by p.productid
 order by highest_quantity_sold desc;
 
 -- ● What is the total revenue generated by each product?
 select p.name,
 sum(od.totalprice) as total_revenue
 from products p 
 join orderdetails od
 on p.productid = od.productid
 group by name;
 
 
 -- ● How do product sales vary by category and supplier?
 select 
 c.categoryname,
 s.suppliername,
 sum(od.quantity) as total_sales
 from orderdetails od
 join products p 
 on p.productid = od.productid
 join categories c 
 on p.categoryid = c.categoryid
 join suppliers s 
 on s.supplierid  = p.supplierid
 group by c.categoryname ,s.suppliername;
 
 
 -- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- ● How many orders have been placed in total?
select*from orders;
select* from orderdetails;
select count(*) as total_orders from orders;

-- ● What is the average value per order?
select avg(order_total) as avg_total_value
from(
 select orderid,
 sum(totalprice) as order_total from orderdetails group by orderid) as temp;
 
 -- ● On which dates were the most orders placed?
 select orderdate, count(*) as total_order  from orders group by orderdate order by total_order desc limit 1;
 
 -- ● What are the monthly trends in order volume and revenue?
 select 
month(o.orderdate) as month,
 count(distinct o.orderid) as total_orders,
 sum(od.totalprice) as total_revenue
 from orders o
join orderdetails od
on o.orderid = od.orderid
 group by month(o.orderdate);
 
 
 -- ● How do order patterns vary across weekdays and weekends
 SELECT 
    CASE 
        WHEN DAYOFWEEK(orderdate) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
select*from suppliers;
select* from products;
-- ● How many suppliers are there in the database?
select count(*) as total_suppliers from suppliers;

-- Which supplier provides the most products?
select s.suppliername,
count(p.productid) as total_products
from suppliers s 
join products p 
 on s.supplierid  = p.productid
 group by suppliername
 order by total_products desc limit 1;

-- ● What is the average price of products from each supplier?
SELECT 
    s.suppliername,
    AVG(p.price) AS avg_price
FROM suppliers s
JOIN products p 
    ON s.supplierid = p.supplierid
GROUP BY s.suppliername;

-- ● Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.supplierid,s.suppliername,
    SUM(od.totalprice) AS total_revenue
FROM orderdetails od
JOIN products p 
    ON od.productid = p.productid
JOIN suppliers s 
    ON p.supplierid = s.supplierid
GROUP BY s.supplierid,suppliername
ORDER BY total_revenue DESC;


-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
select* from employees;
select*from orders;
-- ● How many employees have processed orders?
select count(distinct employeeid) as total_orders from orders;

-- ● Which employees have handled the most orders?
SELECT 
    e.employeeid,
    e.name,
    COUNT(o.orderid) AS total_orders
FROM employees e
JOIN orders o 
    ON e.employeeid = o.employeeid
GROUP BY e.employeeid, e.name
ORDER BY total_orders DESC;

-- ● What is the total sales value processed by each employee?
-- Total sales per employee
select 
e.employeeid,
e.name,
sum(od.totalprice) as total_sales
from employees e
join orders o
on e.employeeid = o.employeeid
join orderdetails od
on o.orderid = od.orderid
group by e.employeeid,e.name;


-- ● What is the average order value handled per employee?
-- Average order value per employee
SELECT 
    e.employeeid,
    e.name,
    AVG(order_total) AS avg_order_value
FROM (
    SELECT 
        o.employeeid,
        o.orderid,
        SUM(od.totalprice) AS order_total
    FROM orders o
    JOIN orderdetails od 
        ON o.orderid = od.orderid
    GROUP BY o.employeeid, o.orderid
) AS temp
JOIN employees e 
    ON temp.employeeid = e.employeeid
GROUP BY e.employeeid, e.name;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.

-- ● What is the relationship between quantity ordered and total price?
SELECT quantity, totalprice FROM orderdetails;

-- ● What is the average quantity ordered per product?
SELECT 
    productid,
    AVG(quantity) AS avg_quantity
FROM orderdetails
GROUP BY productid;

-- ● How does the unit price vary across products and orders?
SELECT 
    p.name,
    od.orderid,
    od.priceeach
FROM orderdetails od
JOIN products p 
    ON od.productid = p.productid
ORDER BY p.name, od.priceeach;

select *from orderdetails;
select*from products;